/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flappyBird;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Nick
 */
public class MenuScore extends javax.swing.JPanel {

    BufferedImage image;
    BufferedImage imageOiseau;
    int birdX = 0;
    int birdY = 0;
    int rotation = 0;
    JFrame jf;
    Timer timer;

    /**
     * Creates new form MenuScore
     */
    public MenuScore(JFrame j) throws IOException {
        initComponents();
        jf = j;
        ImageIcon trash = new ImageIcon("trash.gif");
        btnTrash.setIcon(trash);
        image = ImageIO.read(new File("background2.jpg"));
        imageOiseau = ImageIO.read(new File("bird.gif"));
        timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                // Rotation information
                rotation += 4;
                if (rotation > 360)
                    rotation = 0;
                repaint();
            }
        },16, 16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblMenuPrincipal = new javax.swing.JLabel();
        lblRejouer = new javax.swing.JLabel();
        lblQuitter = new javax.swing.JLabel();
        try {
            top10Joueur2 = new flappyBird.Top10Joueur();
        } catch (java.lang.Exception e1) {
            e1.printStackTrace();
        }
        btnTrash = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tiger Rag LET", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Tableau des scores");

        lblMenuPrincipal.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        lblMenuPrincipal.setText("Retour au menu principal");
        lblMenuPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMenuPrincipalMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMenuPrincipalMousePressed(evt);
            }
        });

        lblRejouer.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        lblRejouer.setText("Rejouer");
        lblRejouer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRejouerMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblRejouerMousePressed(evt);
            }
        });

        lblQuitter.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        lblQuitter.setText("Quitter");
        lblQuitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuitterMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblQuitterMousePressed(evt);
            }
        });

        top10Joueur2.setOpaque(false);
        top10Joueur2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                top10Joueur2MouseEntered(evt);
            }
        });

        btnTrash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(top10Joueur2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRejouer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblQuitter)
                                .addGap(45, 45, 45))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btnTrash, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(top10Joueur2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTrash, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRejouer)
                    .addComponent(lblQuitter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMenuPrincipal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblMenuPrincipalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuPrincipalMouseEntered
        birdX = 10;
        birdY = 485;
    }//GEN-LAST:event_lblMenuPrincipalMouseEntered

    private void lblMenuPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuPrincipalMousePressed
        jf.dispose();
        timer.cancel();
        final JFrame nvJf = new JFrame("Menu");
        nvJf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        nvJf.setSize(426, 330);
        try {
            nvJf.add(new MenuIntro(nvJf));
        } catch (IOException ex) {
            
        }
        nvJf.setVisible(true);
    }//GEN-LAST:event_lblMenuPrincipalMousePressed

    private void lblRejouerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRejouerMouseEntered
        birdX = 10;
        birdY = 435;
    }//GEN-LAST:event_lblRejouerMouseEntered

    private void lblRejouerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRejouerMousePressed
        jf.dispose();
        timer.cancel();
        flappyBird.Fenetre f = new flappyBird.Fenetre();
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.setVisible(true);
    }//GEN-LAST:event_lblRejouerMousePressed

    private void lblQuitterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuitterMouseEntered
        birdX = 230;
        birdY = 435;
    }//GEN-LAST:event_lblQuitterMouseEntered

    private void lblQuitterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuitterMousePressed
        System.exit(0);
    }//GEN-LAST:event_lblQuitterMousePressed

    private void top10Joueur2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_top10Joueur2MouseEntered
        birdX = 5;
        birdY = 80;
    }//GEN-LAST:event_top10Joueur2MouseEntered

    private void btnTrashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrashActionPerformed
        int n = JOptionPane.showConfirmDialog(jf,"Attention, vous allez supprimer TOUS les score, vous êtes sûr?","Suppression!",JOptionPane.YES_NO_OPTION);
        if (n ==  JOptionPane.YES_OPTION)
        {
            SelectJoueur sj = new SelectJoueur();
            try {
                sj.supprimerTout();
            } catch (SQLException ex) {
                Logger.getLogger(MenuScore.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(MenuScore.class.getName()).log(Level.SEVERE, null, ex);
            }
            jf.dispose();
            try {
                JFrame j = new JFrame("Score");
                j.add(new MenuScore(jf));
                j.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                j.setSize(475, 600);
                j.setVisible(true);
                
            } catch (IOException ex) {
                Logger.getLogger(MenuScore.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnTrashActionPerformed


    public void paintComponent(Graphics g){
        double rotationRequired = Math.toRadians (rotation);
        AffineTransform tx = AffineTransform.getRotateInstance(rotationRequired, imageOiseau.getWidth()/2, imageOiseau.getHeight()/2);
        AffineTransformOp op = new AffineTransformOp(tx, AffineTransformOp.TYPE_BILINEAR);

        // Drawing the rotated image at the required drawing locations
          g.drawImage(image, 0, 0, this.getWidth(), this.getHeight(), null);
          g.drawImage(op.filter(imageOiseau, null), birdX, birdY,50,50, null);

      }

      public void paint (Graphics g){
        Graphics g2;            //dessiner dans un autre graphique pour éviter que ca flash
        Dimension d = getSize();//
        Image offImage;
        
        offImage = createImage(d.width, d.height);
        g2=offImage.getGraphics();
        
        
        super.paint(g2);
        g.drawImage(offImage,0 ,0, this);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTrash;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblMenuPrincipal;
    private javax.swing.JLabel lblQuitter;
    private javax.swing.JLabel lblRejouer;
    private flappyBird.Top10Joueur top10Joueur2;
    // End of variables declaration//GEN-END:variables
}
