/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flappyBird;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Nick
 */
public class NewScore extends javax.swing.JPanel {

    /**
     * Creates new form NewScore
     */
    BufferedImage image;
    BufferedImage imageOiseau;
    int birdX = 20;
    int birdY = 50;
    int rotation = 0;
    JFrame jf;
    int score = 0;
    Timer timer;
    
    public NewScore(JFrame jf, int score) throws IOException {
        initComponents();
        this.jf = jf;
        this.score = score;
        tbxNom.setDocument(new JTextFieldLimit(20));
        image = ImageIO.read(new File("background2.jpg"));
        imageOiseau = ImageIO.read(new File("bird.gif"));
        lblScore.setText("Score : " + score);
        
        timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                // Rotation information
                rotation += 16;
                if (rotation > 360)
                    rotation = 0;
                repaint();
            }
        },16, 16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRecordBattu = new javax.swing.JLabel();
        tbxNom = new javax.swing.JTextField();
        lblScore = new javax.swing.JLabel();
        lblEntrerVotreNom = new javax.swing.JLabel();
        lblAnnuler = new javax.swing.JLabel();
        lblOk = new javax.swing.JLabel();

        lblRecordBattu.setFont(new java.awt.Font("Tiger Rag LET", 1, 48)); // NOI18N
        lblRecordBattu.setForeground(new java.awt.Color(153, 0, 0));
        lblRecordBattu.setText("Record battu!");

        tbxNom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tbxNom.setText("jTextField1");
        tbxNom.setMaximumSize(new java.awt.Dimension(30, 1));
        tbxNom.setMinimumSize(new java.awt.Dimension(1, 1));

        lblScore.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblScore.setText("Score:");
        lblScore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblScoreMouseEntered(evt);
            }
        });

        lblEntrerVotreNom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEntrerVotreNom.setText("Entrer votre nom!");

        lblAnnuler.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        lblAnnuler.setText("Annuler");
        lblAnnuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAnnulerMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAnnulerMousePressed(evt);
            }
        });

        lblOk.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        lblOk.setText("Ok");
        lblOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOkMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblOkMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 41, Short.MAX_VALUE)
                .addComponent(lblRecordBattu)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(lblEntrerVotreNom)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(tbxNom, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lblScore)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAnnuler)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblRecordBattu, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEntrerVotreNom)
                .addGap(39, 39, 39)
                .addComponent(tbxNom, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnnuler)
                    .addComponent(lblOk))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblAnnulerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnnulerMouseEntered
        birdX = 190;
        birdY = 220;
    }//GEN-LAST:event_lblAnnulerMouseEntered

    private void lblAnnulerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnnulerMousePressed

        //default icon, custom title
        int n = JOptionPane.showConfirmDialog(jf,"Vous êtes sur de ne pas vouloir entrer de nom?","Aucune nom entrer!",JOptionPane.YES_NO_OPTION);
        if (n ==  JOptionPane.YES_OPTION)
        {
            jf.dispose();
            timer.cancel();
        JFrame newJf = new JFrame("Top score!");
        newJf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        newJf.setSize(475, 600);
        try {
            newJf.add(new flappyBird.MenuScore(newJf));
            newJf.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MenuIntro.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
    }//GEN-LAST:event_lblAnnulerMousePressed

    private void lblOkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOkMouseEntered
        birdX = 5;
        birdY = 220;
    }//GEN-LAST:event_lblOkMouseEntered

    private void lblOkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOkMousePressed
        if (tbxNom.getText().isEmpty())
            JOptionPane.showMessageDialog(jf, "Vous devez entrer votre nom!");
        else
        {
            SelectJoueur sj = new SelectJoueur();
            try {
                sj.ajouterJoueur(tbxNom.getText(), score);
            } catch (Exception ex) {
                Logger.getLogger(NewScore.class.getName()).log(Level.SEVERE, null, ex);
            }
            jf.dispose();
            timer.cancel();
            JFrame newJf = new JFrame("Top score!");
            newJf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            newJf.setSize(430, 600);
            try {
                newJf.add(new flappyBird.MenuScore(newJf));
                newJf.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(MenuIntro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lblOkMousePressed

    private void lblScoreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblScoreMouseEntered
        birdX = 20;
        birdY = 50;
    }//GEN-LAST:event_lblScoreMouseEntered

     public void paintComponent(Graphics g){
        double rotationRequired = Math.toRadians (rotation);
        AffineTransform tx = AffineTransform.getRotateInstance(rotationRequired, imageOiseau.getWidth()/2, imageOiseau.getHeight()/2);
        AffineTransformOp op = new AffineTransformOp(tx, AffineTransformOp.TYPE_BILINEAR);

        // Drawing the rotated image at the required drawing locations
          g.drawImage(image, 0, 0, this.getWidth(), this.getHeight(), null);
          g.drawImage(op.filter(imageOiseau, null), birdX, birdY,50,50, null);

      }

      public void paint (Graphics g){
        Graphics g2;            //dessiner dans un autre graphique pour éviter que ca flash
        Dimension d = getSize();//
        Image offImage;
        
        offImage = createImage(d.width, d.height);
        g2=offImage.getGraphics();
        
        
        super.paint(g2);
        g.drawImage(offImage,0 ,0, this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAnnuler;
    private javax.swing.JLabel lblEntrerVotreNom;
    private javax.swing.JLabel lblOk;
    private javax.swing.JLabel lblRecordBattu;
    private javax.swing.JLabel lblScore;
    private javax.swing.JTextField tbxNom;
    // End of variables declaration//GEN-END:variables
}
