/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flappyBird;

import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author Nick
 */
public class Top10Joueur extends javax.swing.JPanel {

    /**
     * Creates new form Top10Joueur
     */
    ArrayList<JoueurBD> tousLesJoueurs;
    ArrayList<JLabel> labelJoueur;
    ArrayList<JLabel> labelScore;
    
    public Top10Joueur() throws Exception {
        initComponents();
        tousLesJoueurs = new ArrayList<>();
        SelectJoueur sj = new SelectJoueur();
        labelJoueur = new ArrayList<>();
        labelScore = new ArrayList<>();
        tousLesJoueurs = sj.getTop10Joueur();
//        try {
//            tousLesJoueurs = sj.getTop10Joueur();
//        } catch (Exception ex) {
//            Logger.getLogger(Top10Joueur.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
        labelJoueur.add(lbljoueur1);
        labelJoueur.add(lbljoueur2);
        labelJoueur.add(lbljoueur3);
        labelJoueur.add(lbljoueur4);
        labelJoueur.add(lbljoueur5);
        labelJoueur.add(lbljoueur6);
        labelJoueur.add(lbljoueur7);
        labelJoueur.add(lbljoueur8);
        labelJoueur.add(lbljoueur9);
        labelJoueur.add(lbljoueur10);
        
        labelScore.add(lblpoint1);
        labelScore.add(lblpoint2);
        labelScore.add(lblpoint3);
        labelScore.add(lblpoint4);
        labelScore.add(lblpoint5);
        labelScore.add(lblpoint6);
        labelScore.add(lblpoint7);
        labelScore.add(lblpoint8);
        labelScore.add(lblpoint9);
        labelScore.add(lblpoint10);
        
        for (int i = 0; i < tousLesJoueurs.size(); i++) {
            labelJoueur.get(i).setText("# " + (i + 1) + " " + tousLesJoueurs.get(i).getJoueur_nom());
            labelScore.get(i).setText(String.valueOf(tousLesJoueurs.get(i).getJoueur_score()));
            
        }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbljoueur1 = new javax.swing.JLabel();
        lblpoint1 = new javax.swing.JLabel();
        lbljoueur2 = new javax.swing.JLabel();
        lblpoint2 = new javax.swing.JLabel();
        lbljoueur3 = new javax.swing.JLabel();
        lblpoint3 = new javax.swing.JLabel();
        lbljoueur4 = new javax.swing.JLabel();
        lblpoint4 = new javax.swing.JLabel();
        lbljoueur5 = new javax.swing.JLabel();
        lblpoint5 = new javax.swing.JLabel();
        lbljoueur6 = new javax.swing.JLabel();
        lblpoint6 = new javax.swing.JLabel();
        lbljoueur7 = new javax.swing.JLabel();
        lblpoint7 = new javax.swing.JLabel();
        lbljoueur8 = new javax.swing.JLabel();
        lblpoint8 = new javax.swing.JLabel();
        lbljoueur9 = new javax.swing.JLabel();
        lblpoint9 = new javax.swing.JLabel();
        lbljoueur10 = new javax.swing.JLabel();
        lblpoint10 = new javax.swing.JLabel();

        lbljoueur1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbljoueur1.setText("#1 nomJoueur");

        lblpoint1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblpoint1.setText("0");

        lbljoueur2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbljoueur2.setText("#2 nomJoueur");

        lblpoint2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblpoint2.setText("0");

        lbljoueur3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbljoueur3.setText("#3 nomJoueur");

        lblpoint3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblpoint3.setText("0");

        lbljoueur4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbljoueur4.setText("#4 nomJoueur");

        lblpoint4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblpoint4.setText("0");

        lbljoueur5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbljoueur5.setText("#5 nomJoueur");

        lblpoint5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblpoint5.setText("0");

        lbljoueur6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbljoueur6.setText("#6 nomJoueur");

        lblpoint6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblpoint6.setText("0");

        lbljoueur7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbljoueur7.setText("#7 nomJoueur");

        lblpoint7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblpoint7.setText("0");

        lbljoueur8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbljoueur8.setText("#8 nomJoueur");

        lblpoint8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblpoint8.setText("0");

        lbljoueur9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbljoueur9.setText("#9 nomJoueur");

        lblpoint9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblpoint9.setText("0");

        lbljoueur10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbljoueur10.setText("#10 nomJoueur");

        lblpoint10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblpoint10.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbljoueur9)
                    .addComponent(lbljoueur10)
                    .addComponent(lbljoueur1)
                    .addComponent(lbljoueur2)
                    .addComponent(lbljoueur3)
                    .addComponent(lbljoueur4)
                    .addComponent(lbljoueur5)
                    .addComponent(lbljoueur6)
                    .addComponent(lbljoueur7)
                    .addComponent(lbljoueur8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblpoint10)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblpoint8)
                        .addComponent(lblpoint7)
                        .addComponent(lblpoint6)
                        .addComponent(lblpoint5)
                        .addComponent(lblpoint4)
                        .addComponent(lblpoint3)
                        .addComponent(lblpoint2)
                        .addComponent(lblpoint1))
                    .addComponent(lblpoint9))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbljoueur1)
                    .addComponent(lblpoint1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbljoueur2)
                    .addComponent(lblpoint2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbljoueur3)
                    .addComponent(lblpoint3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbljoueur4)
                    .addComponent(lblpoint4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbljoueur5)
                    .addComponent(lblpoint5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbljoueur6)
                    .addComponent(lblpoint6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbljoueur7)
                    .addComponent(lblpoint7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbljoueur8)
                    .addComponent(lblpoint8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbljoueur9)
                    .addComponent(lblpoint9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbljoueur10)
                    .addComponent(lblpoint10))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbljoueur1;
    private javax.swing.JLabel lbljoueur10;
    private javax.swing.JLabel lbljoueur2;
    private javax.swing.JLabel lbljoueur3;
    private javax.swing.JLabel lbljoueur4;
    private javax.swing.JLabel lbljoueur5;
    private javax.swing.JLabel lbljoueur6;
    private javax.swing.JLabel lbljoueur7;
    private javax.swing.JLabel lbljoueur8;
    private javax.swing.JLabel lbljoueur9;
    private javax.swing.JLabel lblpoint1;
    private javax.swing.JLabel lblpoint10;
    private javax.swing.JLabel lblpoint2;
    private javax.swing.JLabel lblpoint3;
    private javax.swing.JLabel lblpoint4;
    private javax.swing.JLabel lblpoint5;
    private javax.swing.JLabel lblpoint6;
    private javax.swing.JLabel lblpoint7;
    private javax.swing.JLabel lblpoint8;
    private javax.swing.JLabel lblpoint9;
    // End of variables declaration//GEN-END:variables
}
